name: Output information
on:
  pull_request:
    types: [opened, edited]
    branches:
      - "dev-*" # dev-new dev-this-is-new
      - main
  workflow_dispatch:
  push:
    branches:
      - "dev-*" # dev-new dev-this-is-new
      - main
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Output Github context
        run: echo "${{ toJSON(github) }}"
