name: Test and deploy workflow
on: [push,workflow_dispatch]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name : Get the code
        uses: actions/checkout@v5
      - name: lint
        run: echo "running the lint"
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Deploy code
        run:  echo "Deploying...."




